export const PRODUCT_RECEIVED = "PRODUCT_RECEIVED";

export const PRODUCT_SET_QUANTITY = "PRODUCT_SET_QUANTITY";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_ADD = "PRODUCT_ADD";

export const CHANGE_CATEGORY_MODAL = "CHANGE_CATEGORY_MODAL";
export const SHOW_MODAL = "SHOW_MODAL";
export const REMOVE_MODAL = "REMOVE_MODAL";

export const ADD_ADDITIVES_TO_CUSTOM_SANDWICH = "ADD_ADDITIVES_TO_CUSTOM_SANDWICH";
export const ADD_CUSTOM_SANDWICH_TO_BASKET = "ADD_CUSTOM_SANDWICH_TO_BASKET";
export const ADD_SELECTED_SANDWICH = "ADD_SELECTED_SANDWICH";
export const REMOVE_CUSTOM_SANDWICH = "REMOVE_CUSTOM_SANDWICH";
export const SET_QUANTITY_CUSTOM_SANDWICH = "SET_QUANTITY_CUSTOM_SANDWICH";
